CREATE DATABASE quotations;

DROP TABLE IF EXISTS quote; 

USE quotations;

CREATE TABLE `quote` (
 id INT NOT NULL AUTO_INCREMENT,
 quotation LONGBLOB NOT NULL,
 CharID VARCHAR(25) NOT NULL,
 url VARCHAR(255) NOT NULL,

 PRIMARY KEY (id)

);

SELECT * FROM quote;

SELECT * FROM quote WHERE CharID = Morty;

SELECT * FROM quote
ORDER BY RAND()
LIMIT 1;

DELETE FROM quote;